//
// Created by hubert25632 on 13.05.22.
//

#ifndef TEMPERATURE_BOX_PROJECT_TEMPCAN_HPP
#define TEMPERATURE_BOX_PROJECT_TEMPCAN_HPP

#include "CanParser_autogenerated.hpp"
#include "CommCAN.hpp"
#include "ReadTemp.hpp"
#include "TaskManager.hpp"

class TempCAN : public SBT::System::PeriodicTask {
    std::vector<std::shared_ptr<ReadTemp>> const readTempTasks;
    SBT::System::Comm::TEMPERATURE_POWERBOX_t temperaturePowerbox;
    uint8_t canPayload[8];

public:
    explicit TempCAN(std::vector<std::shared_ptr<ReadTemp>> readTempTasks);
    void initialize() override;
    void run() override;
};

#endif // TEMPERATURE_BOX_PROJECT_TEMPCAN_HPP
